"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['pyRouter.py']
DATA_FILES = ['sources.csv', 'destinations.csv']
OPTIONS = {'argv_emulation': True,
 'iconfile': '/Users/darias/dev/pyRouter copy/icon.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
